-- Round 14 Agent 2: endereço, bloqueio de contato
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS cep TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS street TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS address_number TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS complement TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS neighborhood TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS is_blocked BOOLEAN DEFAULT false;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS block_reason TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS blocked_at TIMESTAMPTZ;
