ALTER TABLE conversations ADD COLUMN IF NOT EXISTS merged_into UUID REFERENCES conversations(id) ON DELETE SET NULL;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS is_merged BOOLEAN DEFAULT FALSE;
