// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjpkrulpokzjihlmevht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqcGtydWxwb2t6amlobG1ldmh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1MjExNTgsImV4cCI6MjA4ODA5NzE1OH0.Hv_NfmAkFPrPhR5uwT-jqPKWe0pw7nvWY34fuEJJh0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});